environment: production

services:
  github:
    baseUrl: https://raw.githubusercontent.com/kschat/

content:
  source: LOCAL
  basePath: ./content

projects:
  - name: Snake
    button: DEMO
    url: https://github.com/kschat/snake/releases

  - name: CSS Parser
    button: READ_MORE

  - name: Pascal Compiler
    button: READ_MORE

  - name: Game of Life
    button: DEMO
    url: https://game-of-life.kyleschattler.com

  - name: Trampoline TS
    button: READ_MORE

  - name: Baby Announcement
    button: READ_MORE

  - name: Dotfiles
    button: READ_MORE

  - name: Personal Website
    button: READ_MORE

  - name: No BuzzFeed
    button: READ_MORE

  - name: Scrum Poker
    button: DEMO
    url: http://scrumpoker.kyleschattler.com

server:
  port: 8080

